[serve]
port = 8010

[tools]
# needs to be aligned with the builder image
sass = "1.50.0 compiled with dart2js 2.16.2"
wasm_bindgen = "0.2.80"
wasm_opt = "version_105"

[[hooks]]
stage = "build"
command = "bash"
command_arguments = ["trunk.d/build.sh"]
